
version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
    - "80:80"
  # If running behind a proxy container, expose the potrs instead
  # and link the proxy container to this one.
  #  expose:
  #  - "80"
    links:
    - mariadb:mariadb
    - postfix:postfix
  # You should use env_file: instead of environment: for your environment
  # variables. Look at the README.md file for a list of available variables
    env_file: .env
    volumes:
      - '/home/stuff/volumes/otrs/config:/opt/otrs/Kernel'
      # Uncomment if using OTRS_ARTICLE_STORAGE_TYPE=ArticleStorageFS
      #- /home/stuff/volumes/otrs/article:/opt/otrs/var/article
      - '/home/stuff/volumes/otrs/skins:/opt/otrs/var/httpd/htdocs/skins/'
      - '/home/stuff/volumes/otrs/backup:/var/otrs/backups'
      - '/home/stuff/volumes/otrs/addons:/opt/otrs/addons'
      - '/home/stuff/volumes/otrs/db_upgrade:/opt/otrs/db_upgrade'
      - '/etc/localtime:/etc/localtime:ro'
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
    - "3306"
    env_file: .env
    volumes:
      - '/home/stuff/volumes/otrs/mysql:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
  postfix:
     image: juanluisbaptiste/postfix:latest
     expose:
     - "25"
     # See juanluisbaptiste/postfix github page for the contents
     # and an explanation of credentials-smtp.
     env_file: .env
